FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# install deps
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# copy project
COPY . /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]