name: Build

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Use your Makefile targets. We override USE_SUDO to avoid sudo in the runner.
      - name: Build & sanity-check via Makefile
        run: |
          make ci USE_SUDO=